version: "3.8"

services:
  frontend:
    networks:
      - flavor-network
    build:
      target: development
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run start

networks:
  flavor-network:
    name: flavor-network
    driver: bridge
