services:
    frontend:
        extends:
            file: docker-compose.yml
            service: frontend
        volumes:
            - ./dist:/usr/src/app/dist
        networks:
            - flavor-network
        build:
            target: production
        environment:
            - NODE_ENV=production

networks:
    flavor-network:
        name: flavor-network
        driver: bridge
